### ISSUE TITLE
Support for custom ScalingMode

### ISSUE THREAD

**Issue by DasLixou** [torsteingrindvik/bevy-vfx-bag#68]
add support for custom ScalingMode. i currently have a scalingmode set in my Camera3dBundle aka PostProcessingInput but it doesnt apply when i use vfx-bag. probably because it is a camera of a camera?

**Comment by torsteingrindvik** [comment]
I can take a look at this.

I also have to look at `ScalingMode` since I haven't used it.
Just to make sure, could you describe what you expect to happen and what actually happens?

**Comment by DasLixou** [comment]
ScalingMode is a thing on the camera that says how it behaves when the target gets resized. the problem seems that the image (target) that it now renderes to doesn't resize to the window size when i get it correctly.

**Comment by DasLixou** [comment]
Without your plugin (ScalingMode works as expected)
![grafik](https://user-images.githubusercontent.com/82600264/202728245-ca007dc3-5cac-419e-85d9-b6f8628d5938.png)

With your plugin (is wrongly scaled)
![grafik](https://user-images.githubusercontent.com/82600264/202728351-e8f2fe9b-1c41-49df-a0c2-234f70d3773d.png)

**Comment by torsteingrindvik** [comment]
Thank you for the details.
I will look into it as soon as I have time.

**Comment by torsteingrindvik** [comment]
I attempted a workaround for this by extracting the orthographic projection from the user's input camera, and propagating that to the spawned cameras.

This _kinda_ fixed it, but there were some other bugs.

But this all boils down to issues due to spawning cameras for effects.
Now with Bevy 0.9 there is a proper way to do post processing.

I am going to port this entire plugin to use that approach, and then there will be no cameras spawned, and I expect the issue to go away.

Therefore I consider this bug blocked on #45 .

**Comment by DasLixou** [comment]
Oh LOL i also started a Little vfx Library today to see how far I can come and also make it not use cameras lmao 🤣.

**Comment by DasLixou** [comment]
@torsteingrindvik seems like i found the issue. Your image to what the camera displays its thing on won't rescale. i made a system that makes it in my library (it currently doesn't show it but it gets piped trough correctly :D ) which resizes the images to the end-target. here if u wanna see: https://github.com/LixouStudios/bevy_vfx/commit/cb8f3c60f50638485c73477aac030cce4f2f6093

**Comment by torsteingrindvik** [comment]
@DasLixou thanks.

I have started on a plugin rework now though so I don't expect this issue to linger for very long.

**Comment by DasLixou** [comment]
> @DasLixou thanks.
> 
> I have started on a plugin rework now though so I don't expect this issue to linger for very long.

Are you going to use RenderGraphs? @torsteingrindvik

**Comment by DasLixou** [comment]
@torsteingrindvik would you make the plugin rework on a public branch? I would like to contribute a little bit :)

**Comment by torsteingrindvik** [comment]
It will use render graphs, and yes it will be public when I have landed on an approach.

**Comment by DasLixou** [comment]
> It will use render graphs, and yes it will be public when I have landed on an approach.

Cool 😎

**Comment by torsteingrindvik** [comment]
After the rework this plugin should behave the same as Bevy proper for scalingmode.
If this is still relevant to you and you try this out let me know how it goes.

**Comment by DasLixou** [comment]
😎
